### ISSUE TITLE
@hyperapp/transitions@^1.0.2' is not in the npm registry.

### ISSUE THREAD

**Issue by darren-211** [zaceno/hyperapp-transitions#21]
![image](https://user-images.githubusercontent.com/12593297/57429149-c7bba800-725d-11e9-8a08-68bd61803a7d.png)
How could you remove it!!!

**Comment by jorgebucaran** [comment]
It's `hyperapp-transitions` now, but I don't know if @zaceno has published it yet. Should be just a matter of waiting until he can.

**Comment by zaceno** [comment]
Yes I'm guessing it happened because Jorge is restructuring how hyperapp-packages are published. Anyway, I just published hyperapp-transitions@1.0.2, so go ahead and try that @darren-211 

Be forewarned: I don't intend to maintain this project any longer (I hit a dead end for v1 of hyperapp with some bugs I couldn't work out, and in v2 it will have to be completely different if I ever do make anything similar).

**Comment by darren-211** [comment]
Thanks a lot.
